# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don' t change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.box_url = "Vagrantfile"
    config.vm.hostname = "my-app"
    config.vm.provider "virtualbox" do |v|
     v.memory = 512
     v.cpus = 1
    end
    config.vm.synced_folder "requirements/", "/srv/requirements/"
    config.vm.define "standalone" do |standalone|
      standalone.vm.hostname = "standalone"
      standalone.vm.network "forwarded_port", host: 8080, guest: 8080
      config.vm.synced_folder ".", "/src/"
      config.vm.provision :"shell", path: "installpuppet.sh"
      standalone.vm.provision :puppet do |puppet|
        puppet.manifests_path = "manifests"
        puppet.manifest_file = "standalone.pp"
    end
  end
 end
